version: "3"

services:

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    user: "0:0"
    networks:
      - mynetwork

  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf/data:/var/lib/telegraf
    depends_on:
      - mqtt-broker
      - influxdb
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'host_ip:10.11.0.6'  # Add your host IP here
    networks:
      - mynetwork

  influxdb-2:
    image: influxdb:2.6-alpine
    env_file:
      - influxv2.env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./influxdb-2/config/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb-2/data:/var/lib/influxdb2
    network_mode: host

  influxdb:
    platform: linux/amd64
    restart: always
    image: influxdb:1.8
    volumes:
      - ./influxdb/data/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mydatabase
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    user: "0"
    env_file:
      - 'grafana.env'
    environment:
      - GF_INSTALL_PLUGINS=grafana-influxdb-flux-datasource,grafana-strava-datasource
      - GF_SECURITY_ADMIN_PASSWORD=<your_grafana_password>
      - GF_FEATURE_TOGGLES_ENABLE=externalServiceAccounts
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/config:/etc/grafana
    network_mode: host

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
      - "11711:11711/udp"
    volumes:
      - ./node-red/data/:/data
    networks:
      - mynetwork

  chronograf:
    image: chronograf:latest
    ports:
      - '8889:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
    networks:
      - mynetwork

volumes:
  influxdb:
  grafana:
  chronograf-storage:

networks:
  mynetwork:
    driver: bridge
