version: "3"
services: 
  influxdb-2:
    image: influxdb:2.6-alpine
    env_file:
      - influxv2.env
    volumes:
      - ./influxdb-2:/var/lib/influxdb2:rw
    ports:
      - "8087:8086"


  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mydatabase
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    user: "0"
    env_file:
      - 'grafana.env'
    environment:
      - GF_INSTALL_PLUGINS=grafana-influxdb-flux-datasource,grafana-strava-datasource
      - GF_SECURITY_ADMIN_PASSWORD=<your_grafana_password>
      - GF_FEATURE_TOGGLES_ENABLE=externalServiceAccounts
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
      - ./grafana/config:/etc/grafana

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
      - "11711:11711/udp"
    volumes:
      - ./node-red/data/:/data

  chronograf:
    image: chronograf:latest
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=password
  
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"

volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:


